runtime: ruby
env: flex
# entrypoint: bundle exec foreman start
# entrypoint: bundle exec rails server -p 8080
# PUBSUB_EMULATOR_HOST=localhost:8085
env_variables:
  SECRET_KEY_BASE: Rails.application.credentials.secret_key_base





###### Below files are part of Pub/sub 
entrypoint: bundle exec ruby app.rb
instance_class: F2
# [START gae_pubsub_yaml]
env_variables:
    PUBSUB_TOPIC: ENV["PUBSUB_TOPIC"]
    # This token is used to verify that requests originate from your
    # application. It can be any sufficiently random string.
    PUBSUB_VERIFICATION_TOKEN: ENV["PUBSUB_VERIFICATION_TOKEN"]
# [END gae_pubsub_yaml]
