runtime: ruby
env: flex

# entrypoint: bundle exec rails server -p 8080
entrypoint: bundle exec foreman start
# PUBSUB_EMULATOR_HOST=localhost:8085

env_variables:
  SECRET_KEY_BASE: Rails.application.credentials.secret_key_base
