# SETUP: Active Job & Cloud Pub/sub 

# Seperate Worker and Application 

runtime: ruby
env: flex

entrypoint: bundle exec rails server -p 8080

env_variables:
  SECRET_KEY_BASE: Rails.application.credentials.secret_key_base




# Shared Worker and Application 

# runtime: ruby
# env: flex

# entrypoint: bundle exec foreman start

# env_variables:
#   REDIS_PROVIDER: REDIS_URL
#   REDIS_URL: redis://[REDIS_IP_ADDRESS]:6379
#   SECRET_KEY_BASE: 




# 1. With ActiveJob and Cloud Pub/Sub
# 2. With ActiveJob and Sidekiq

